project_name: "whosthere"
version: 2

before:
  hooks:
    - go mod tidy
    - go generate

# generate them ourselves to avoid issues with cross-compilation
# goreleaser can only upload the checksum once, and within the context it doesn't have the other builds available
checksum:
  disable: true

builds:
  - main: ./main.go
    binary: whosthere
    goos: ["linux"]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w -X main.versionStr={{.Version}}
      - -X main.commitStr={{ .Commit }}
      - -X main.dateStr={{ .Date }}
    env:
      # The CGO_ENABLED=1 is required for clipboard support
      # see https://github.com/golang-design/clipboard
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: "arm64"
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: "386"
        env:
          - CC=i686-linux-gnu-gcc
      - goos: linux
        goarch: "amd64"
        env:
          - CC=gcc

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "demo", "^hugo:", "Merge pull request", "Merge branch"]


